service: serverless-crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:<resource_id>:table/TodoTable

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          method: get
          path: /todos
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          method: get
          path: /todo/{id}
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          method: put
          path: /todo/{id}
  deleteTodo:
    handler: src/deleteTodo.handler
    events:
      - http:
          method: delete
          path: /todo/{id}

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
